site_name: Citrix XenServer 7.3 CR Management API Reference
site_description: Citrix XenServer 7.3 CR Management API Reference
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Introduction: index.md
- Wire Protocol for Remote API Calls: wire-protocol.md
- VM Lifecycle: vm-lifecycle.md
- API Reference: api-ref-autogen.md
