site_name: Citrix XenServer Management API
site_description: Reference guide for Citrix XenServer Management API
theme_dir: citrix-sdk
#theme: mkdocs
#repo_url: https://github.com/ajitchelat/AppDNA-SDK.git
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Management API: index.md
